### ISSUE TITLE
steep has totally wrong scope in class_eval

### ISSUE THREAD

**Issue by p-datadog** [soutaro/steep#1232]
When a module augments some class's functionality via `class_eval`, steep appears to completely overlook the fact that inside `class_eval`, `self` is the target class and not the module that contains the augmenting logic. Example:

```
class Base
  def self.foo
    puts 'hello foo'
  end
end

module Mod
  def self.augment(base)
    base.class_eval do
      foo
    end
  end
end

Mod.augment(Base)
```

sig:
```
class Base
  def self.foo: () -> untyped
end

module Mod
  def self.augment: (untyped base) -> untyped
end
```

The above code executes and prints "hello foo", but fails steep check:
```
class_eval.rb:10:6: [error] Type `singleton(::Mod)` does not have method `foo`
│ Diagnostic ID: Ruby::NoMethod
│
└       foo
        ~~~

```

Note that steep tries to find `foo` on `Mod` which is totally incorrect.

Conversely, steep is perfectly happy with the following code and type definition:

```
class Base2
end

module Mod2
  def foo
    puts 'hello foo'
  end

  def self.augment(base)
    base.class_eval do
      foo
    end
  end
end

Mod2.augment(Base2)
```
```
class Base2
end

module Mod2
  def self.augment: (untyped base) -> untyped
  def foo: () -> untyped
end
```
Here, I put `foo` into the module. But, obviously, the above is not valid Ruby:
```
% ruby class_eval_2.rb 
class_eval_2.rb:11:in `block in augment': undefined local variable or method `foo' for class Base2 (NameError)

      foo
      ^^^
	from class_eval_2.rb:10:in `class_eval'
	from class_eval_2.rb:10:in `augment'
	from class_eval_2.rb:16:in `<main>'
```

**Comment by ksss** [comment]
First, the `class_eval` type is not checked because the `base` is `untyped`.

But if you change `base` to `singleton(Base)` it will not work as expected.
I think, We should add self type to block in `Module#class_eval` like this.

```rbs
  def class_eval: (String arg0, ?String filename, ?Integer lineno) -> untyped
                | [U] () { (self m) [self: self] -> U } -> U
```

**Comment by p-datadog** [comment]
OK, I changed the type definition to:
```
class Base
  def self.foo: () -> untyped
end

module Mod
  def self.augment: (singleton(Base) base) -> untyped
end
```

But steep thinks that base is singleton(Mod), not singleton(Base) as declared:
```
class_eval.rb:10:6: [error] Type `singleton(::Mod)` does not have method `foo`
│ Diagnostic ID: Ruby::NoMethod
│
└       foo
        ~~~

```

**Comment by ksss** [comment]
@p-datadog 
I fixed this issue by https://github.com/ruby/rbs/pull/2029 .
Could you try the master branch of rbs?

**Comment by p-datadog** [comment]
I thought I did but I guess without `branch: 'master'`, `github: 'soutaro/steep'` does not request master branch?

I checked again and the issue is half fixed. IF I declare the type of `base`, steep works correctly:

```

module Mod
  def self.augment: (singleton(Base) base) -> untyped
end
```

However, in the code I am working with, `base` is an anonymous class and to type it at all would be a non-trivial undertaking.

With `base` declared as `untyped`, steep's behavior is incorrect: it assumes that `self` is `singleton(Mod)`, whereas in reality `self` should in fact be `untyped`. I don't know if there are other cases where it's valid to transfer `singleton(Mod)` into `base` as its type, this is as far as I can tell not a valid operation in the case being discussed here in this ticket.

**Comment by ksss** [comment]
If you can't change it from `untyped`, you can use the `@type` annotation or ignore type checking with `steep:ignore`.

https://github.com/soutaro/steep/pull/1034
