### ISSUE TITLE
 Steep 1.9.0 and 1.9.2 stuck when running check 

### ISSUE THREAD

**Issue by kazuminn** [soutaro/steep#1434]
When I execute the check command, so I see some log, so I execute ctrl + C, so I see a deadlock log, so I can't use check.
Why reason, why.

My enviroment
OS : Ubunt 24.04
CPU : intel i5
Ruby : 3.3.6
steep version : at least 1.9.0 and 1.9.2

related issue : https://github.com/soutaro/steep/issues/1162

command: bundle exec steep check

<details>
2024-12-20 17:24:29.721: FATAL: [Steep 1.9.2] [typecheck:typecheck@2] [background] Unexpected error: RuntimeError
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rbs-3.7.0/lib/rbs/definition_builder/ancestor_builder.rb:222:in `one_instance_ancestors'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/signature_service.rb:288:in `block (4 levels) in update_env'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/signature_service.rb:308:in `rescue_rbs_error'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/signature_service.rb:288:in `block (3 levels) in update_env'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/signature_service.rb:287:in `each_key'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/signature_service.rb:287:in `block (2 levels) in update_env'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep.rb:208:in `measure'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/signature_service.rb:286:in `block in update_env'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `block in tagged'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `tagged'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/signature_service.rb:236:in `update_env'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/signature_service.rb:216:in `block (2 levels) in update'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep.rb:208:in `measure'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/signature_service.rb:215:in `block in update'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `block in tagged'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `tagged'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/signature_service.rb:185:in `update'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:265:in `block (3 levels) in update_signature'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `block in tagged'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `tagged'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:257:in `block (2 levels) in update_signature'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:256:in `each'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:256:in `block in update_signature'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `block in tagged'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `tagged'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:249:in `update_signature'
2024-12-20 17:24:29.721: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:146:in `block in update'
2024-12-20 17:24:29.722: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep.rb:208:in `measure'
2024-12-20 17:24:29.722: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:145:in `update'
2024-12-20 17:24:29.722: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/type_check_worker.rb:162:in `handle_job'
2024-12-20 17:24:29.722: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
2024-12-20 17:24:29.722: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `block in tagged'
2024-12-20 17:24:29.722: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-20 17:24:29.722: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `tagged'
2024-12-20 17:24:29.722: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/base_worker.rb:46:in `block in run'
2024-12-20 17:24:29.723: FATAL: [Steep 1.9.2] [typecheck:typecheck@2] [background] Unexpected error: #<KeyError: key not found: #<Pathname:app/models/accuracy.rb>>
2024-12-20 17:24:29.723: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:238:in `fetch'
2024-12-20 17:24:29.723: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:238:in `block (2 levels) in typecheck_source'
2024-12-20 17:24:29.723: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep.rb:208:in `measure'
2024-12-20 17:24:29.723: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:233:in `block in typecheck_source'
2024-12-20 17:24:29.723: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `block in tagged'
2024-12-20 17:24:29.723: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-20 17:24:29.723: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `tagged'
2024-12-20 17:24:29.723: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:232:in `typecheck_source'
2024-12-20 17:24:29.723: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/type_check_worker.rb:196:in `handle_job'
2024-12-20 17:24:29.723: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
2024-12-20 17:24:29.723: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `block in tagged'
2024-12-20 17:24:29.723: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-20 17:24:29.723: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `tagged'
2024-12-20 17:24:29.723: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/base_worker.rb:46:in `block in run'
2024-12-20 17:24:29.724: FATAL: [Steep 1.9.2] [typecheck:typecheck@2] [background] Unexpected error: #<KeyError: key not found: #<Pathname:app/models/application_record.rb>>
2024-12-20 17:24:29.724: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:238:in `fetch'
2024-12-20 17:24:29.724: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:238:in `block (2 levels) in typecheck_source'
2024-12-20 17:24:29.724: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep.rb:208:in `measure'
2024-12-20 17:24:29.724: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:233:in `block in typecheck_source'
2024-12-20 17:24:29.724: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `block in tagged'
2024-12-20 17:24:29.724: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-20 17:24:29.724: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `tagged'
2024-12-20 17:24:29.724: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:232:in `typecheck_source'
2024-12-20 17:24:29.724: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/type_check_worker.rb:196:in `handle_job'
2024-12-20 17:24:29.724: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
2024-12-20 17:24:29.724: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `block in tagged'
2024-12-20 17:24:29.724: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-20 17:24:29.724: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `tagged'
2024-12-20 17:24:29.724: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/base_worker.rb:46:in `block in run'
2024-12-20 17:24:29.725: FATAL: [Steep 1.9.2] [typecheck:typecheck@2] [background] Unexpected error: #<KeyError: key not found: #<Pathname:app/models/comment.rb>>
2024-12-20 17:24:29.725: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:238:in `fetch'
2024-12-20 17:24:29.725: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:238:in `block (2 levels) in typecheck_source'
2024-12-20 17:24:29.725: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep.rb:208:in `measure'
2024-12-20 17:24:29.725: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:233:in `block in typecheck_source'
2024-12-20 17:24:29.725: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `block in tagged'
2024-12-20 17:24:29.725: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-20 17:24:29.725: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `tagged'
2024-12-20 17:24:29.725: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:232:in `typecheck_source'
2024-12-20 17:24:29.725: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/type_check_worker.rb:196:in `handle_job'
2024-12-20 17:24:29.725: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
2024-12-20 17:24:29.725: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `block in tagged'
2024-12-20 17:24:29.725: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-20 17:24:29.725: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `tagged'
2024-12-20 17:24:29.725: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/base_worker.rb:46:in `block in run'
2024-12-20 17:24:29.726: FATAL: [Steep 1.9.2] [typecheck:typecheck@2] [background] Unexpected error: #<KeyError: key not found: #<Pathname:app/models/commitment.rb>>
2024-12-20 17:24:29.726: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:238:in `fetch'
2024-12-20 17:24:29.726: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:238:in `block (2 levels) in typecheck_source'
2024-12-20 17:24:29.726: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep.rb:208:in `measure'
2024-12-20 17:24:29.726: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/services/type_check_service.rb:233:in `block in typecheck_source'
2024-12-20 17:24:29.726: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `block in tagged'
2024-12-20 17:24:29.726: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:38:in `tagged'
2024-12-20 17:24:29.726: ERROR: [Steep 1.9.2] [typecheck:typecheck@2] [background]   /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-8.0.1/lib/active_support/tagged_logging.rb:143:in `tagged'

</details>

after ctrl + C

```
.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/base_worker.rb:91:in `join': No live threads left. Deadlock? (fatal)
2 threads, 2 sleeps current:0x00006258efc26130 main thread:0x00006258efc26130
* #<Thread:0x000076009afca9c0 sleep_forever>
   rb_thread_t:0x00006258efc26130 native:0x000076009ba98780 int:0
   
* #<Thread:0x000076007f361e88 /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/base_worker.rb:42 sleep_forever>
   rb_thread_t:0x00006258f1807da0 native:0x000076007efbf6c0 int:0
    depended by: tb_thread_id:0x00006258efc26130
 ```

```
ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/base_worker.rb:91:in `join': No live threads left. Deadlock? (fatal)
2 threads, 2 sleeps current:0x000056a8b35ed130 main thread:0x000056a8b35ed130
* #<Thread:0x000071c9a657a9e0 sleep_forever>
   rb_thread_t:0x000056a8b35ed130 native:0x000071c9a7059780 int:0
   
* #<Thread:0x000071c98a9302b8 /home/kazumi/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/steep-1.9.2/lib/steep/server/base_worker.rb:42 sleep_forever>
   rb_thread_t:0x000056a8b421a760 native:0x000071c98a49e6c0 int:0
    depended by: tb_thread_id:0x000056a8b35ed130


```

Thanks for reading.

**Comment by kazuminn** [comment]
I have more error log.
a error log is huge, so I can't paste huge error log, so I paste a bit log.
if you would like to get more my error log, so tell me that.

thanks.
