### ISSUE TITLE
`steep check` fails with Unexpected error on a code that uses numbered block parameters

### ISSUE THREAD

**Issue by 0exp** [soutaro/steep#285]
### Overview

When you use `numbered block parameters` inside your procs in your code the command `steep check` fails on code-parsing step (as i understand).

```
steep: 0.39.0
ruby: 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
```

### Example

```ruby
# lib/simple_script.rb

[''].each { puts _1 }
```

```ruby
# Steepfile

target :lib do
  signature "sig" # empty directory
  check "lib"
end
```

<details>
<summary>Gemfile</summary>

```ruby
 # frozen_string_literal: true

source "https://rubygems.org"

gem 'rbs'
gem 'steep'
```

</details>

<details>
<summary>Gemfile.lock</summary>

```ruby
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (6.1.0)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    ast (2.4.1)
    ast_utils (0.3.0)
      parser (~> 2.4)
      thor (>= 0.19)
    concurrent-ruby (1.1.7)
    ffi (1.14.2)
    i18n (1.8.5)
      concurrent-ruby (~> 1.0)
    language_server-protocol (3.15.0.1)
    listen (3.3.3)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    minitest (5.14.2)
    parser (2.7.2.0)
      ast (~> 2.4.1)
    rainbow (3.0.0)
    rb-fsevent (0.10.4)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rbs (1.0.0)
    steep (0.39.0)
      activesupport (>= 5.1)
      ast_utils (~> 0.3.0)
      language_server-protocol (~> 3.15.0.1)
      listen (~> 3.0)
      parser (~> 2.7.0)
      rainbow (>= 2.2.2, < 4.0)
      rbs (~> 1.0.0)
    thor (1.0.1)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    zeitwerk (2.4.2)

PLATFORMS
  x86_64-darwin-20

DEPENDENCIES
  rbs
  steep

BUNDLED WITH
   2.2.3

```

</details>

---

```shell
➜ bundle exec steep check

[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb] Unexpected error: #<RuntimeError: #synthesize should return an instance of Pair: Array, node=s(:numblock,
  s(:send,
    s(:array,
      s(:str, "")), :each), 1,
  s(:send, nil, :puts,
    s(:lvar, _1@1)))>
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/type_construction.rb:2197:in `block (2 levels) in synthesize'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   <internal:kernel>:90:in `tap'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/type_construction.rb:2193:in `block in synthesize'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/type_construction.rb:649:in `synthesize'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/source_file.rb:83:in `type_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/source_file.rb:95:in `block in type_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/source_file.rb:118:in `parse'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/source_file.rb:94:in `type_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:227:in `block (2 levels) in run_type_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:226:in `block in run_type_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:225:in `each'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:225:in `run_type_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:110:in `block (4 levels) in type_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep.rb:147:in `measure'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:109:in `block (3 levels) in type_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:182:in `load_signatures'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:108:in `block (2 levels) in type_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep.rb:147:in `measure'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:107:in `block in type_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:106:in `type_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/drivers/utils/driver_helper.rb:19:in `block (2 levels) in type_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/drivers/utils/driver_helper.rb:18:in `block in type_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/drivers/utils/driver_helper.rb:17:in `each'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/drivers/utils/driver_helper.rb:17:in `type_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/drivers/check.rb:27:in `run'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/cli.rb:91:in `process_check'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/cli.rb:50:in `run'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/exe/steep:11:in `<top (required)>'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/bin/steep:23:in `load'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/bin/steep:23:in `<top (required)>'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `load'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:28:in `run'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli.rb:497:in `exec'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/bin/bundle:23:in `load'
[Steep 0.39.0] [target=lib] [target#type_check(target_sources: [lib/script.rb], validate_signatures: true)] [path=lib/script.rb]   /Users/exclusive/.rbenv/versions/3.0.0/bin/bundle:23:in `<main>'
[Steep 0.39.0] [target=lib] Unexpected error: #<RuntimeError: #synthesize should return an instance of Pair: Array, node=s(:numblock,
  s(:send,
    s(:array,
      s(:str, "")), :each), 1,
  s(:send, nil, :puts,
    s(:lvar, _1@1)))>
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/type_construction.rb:2197:in `block (2 levels) in synthesize'
[Steep 0.39.0] [target=lib]   <internal:kernel>:90:in `tap'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/type_construction.rb:2193:in `block in synthesize'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/type_construction.rb:649:in `synthesize'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/source_file.rb:83:in `type_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/source_file.rb:95:in `block in type_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/source_file.rb:118:in `parse'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/source_file.rb:94:in `type_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:227:in `block (2 levels) in run_type_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:226:in `block in run_type_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:225:in `each'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:225:in `run_type_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:110:in `block (4 levels) in type_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep.rb:147:in `measure'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:109:in `block (3 levels) in type_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:182:in `load_signatures'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:108:in `block (2 levels) in type_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep.rb:147:in `measure'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:107:in `block in type_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/project/target.rb:106:in `type_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/drivers/utils/driver_helper.rb:19:in `block (2 levels) in type_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/drivers/utils/driver_helper.rb:18:in `block in type_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/drivers/utils/driver_helper.rb:17:in `each'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/drivers/utils/driver_helper.rb:17:in `type_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/drivers/check.rb:27:in `run'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/cli.rb:91:in `process_check'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/lib/steep/cli.rb:50:in `run'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/steep-0.39.0/exe/steep:11:in `<top (required)>'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/bin/steep:23:in `load'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/bin/steep:23:in `<top (required)>'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `load'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:28:in `run'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli.rb:497:in `exec'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/bin/bundle:23:in `load'
[Steep 0.39.0] [target=lib]   /Users/exclusive/.rbenv/versions/3.0.0/bin/bundle:23:in `<main>'
```

**Comment by soutaro** [comment]
Moved to #336
