### ISSUE TITLE
`rbs validate` error with `rbs collection`

### ISSUE THREAD

**Issue by ybiquitous** [soutaro/steep#432]
Hi there, enjoying RubyKaigi 2021 Takeout? Thanks for implementing the nice feature `rbs collection`! 😄 

---

When I try the `rbs collection` integration with Steep #420 (merged with 0673d88), I encounter the following error on running `rbs validate`:

```
.gem_rbs_collection/activesupport/6.0/activesupport-generated.rbs:6153:2...6153:25: Unknown method alias name: xmlschema => rfc3339 (::Time) (RBS::UnknownMethodAliasError)
```

If this problem is not due to Steep, so feel free to close this issue!

### `Gemfile`

```ruby
source "https://rubygems.org"

gem "steep", github: "soutaro/steep", ref: "0673d88"
gem "rbs", "1.6.2"
```

### `Steepfile`

```ruby
target :lib do
  check "*.rb"
end
```

### `rbs_collection.yaml`

```yaml
# Download sources
sources:
  - name: ruby/gem_rbs_collection
    remote: https://github.com/ruby/gem_rbs_collection.git
    revision: main
    repo_dir: gems

# A directory to install the downloaded RBSs
path: .gem_rbs_collection

gems:
  # Skip loading rbs gem's RBS.
  # It's unnecessary if you don't use rbs as a library.
  - name: rbs
    ignore: true
```

### Running commands

1. Run `bundle install`
2. Run `bundle exec rbs collection install`
3. Run `bundle exec rbs validate`

```
warning: rbs collection is experimental, and the behavior may change until RBS v2.0
warning: rbs collection is experimental, and the behavior may change until RBS v2.0
bundler: failed to load command: rbs (/Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/bin/rbs)
bundler: failed to load command: rbs (/Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/bin/rbs)
/Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder.rb:559:in `block in define_methods': .gem_rbs_collection/activesupport/6.0/activesupport-generated.rbs:6153:2...6153:25: Unknown method alias name: xmlschema => rfc3339 (::Time) (RBS::UnknownMethodAliasError)
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder/method_builder.rb:50:in `block in each'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder/method_builder.rb:67:in `each_value'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder/method_builder.rb:67:in `tsort_each_node'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:316:in `each_strongly_connected_component'
/Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder.rb:559:in `block in define_methods': .gem_rbs_collection/activesupport/6.0/activesupport-generated.rbs:6153:2...6153:25: Unknown method alias name: xmlschema => rfc3339 (::Time) (RBS::UnknownMethodAliasError)
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder/method_builder.rb:50:in `block in each'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder/method_builder.rb:67:in `each_value'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder/method_builder.rb:67:in `tsort_each_node'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:316:in `each_strongly_connected_component'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder/method_builder.rb:45:in `each'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder.rb:550:in `define_methods'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder.rb:214:in `block (2 levels) in build_instance'
	from <internal:kernel>:90:in `tap'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder.rb:146:in `block in build_instance'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder.rb:780:in `try_cache'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder.rb:136:in `build_instance'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/cli.rb:435:in `block in run_validate'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/cli.rb:433:in `each_key'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/cli.rb:433:in `run_validate'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/cli.rb:125:in `run'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/exe/rbs:7:in `<top (required)>'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/bin/rbs:23:in `load'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/bin/rbs:23:in `<top (required)>'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:480:in `exec'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder/method_builder.rb:45:in `each'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder.rb:550:in `define_methods'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder.rb:214:in `block (2 levels) in build_instance'
	from <internal:kernel>:90:in `tap'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder.rb:146:in `block in build_instance'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder.rb:780:in `try_cache'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/definition_builder.rb:136:in `build_instance'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/cli.rb:435:in `block in run_validate'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/cli.rb:433:in `each_key'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/cli.rb:433:in `run_validate'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/lib/rbs/cli.rb:125:in `run'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/gems/rbs-1.6.2/exe/rbs:7:in `<top (required)>'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/bin/rbs:23:in `load'
	from /Users/masafumi.koba/tmp/steep-with-rbs-collection/vendor/bundle/ruby/3.0.0/bin/rbs:23:in `<top (required)>'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:480:in `exec'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:24:in `start'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.0.dev/exe/bundle:49:in `block in <top (required)>'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.0.dev/exe/bundle:37:in `<top (required)>'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/bin/bundle:23:in `load'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/bin/bundle:23:in `<main>'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:24:in `start'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.0.dev/exe/bundle:49:in `block in <top (required)>'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.0.dev/exe/bundle:37:in `<top (required)>'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/bin/bundle:23:in `load'
	from /Users/masafumi.koba/.rbenv/versions/3.0.2/bin/bundle:23:in `<main>'
```

## Environment

- ruby: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]`
- bundler: `2.3.0.dev`
- steep: `0.46.0`
- rbs: `1.6.2`

**Comment by pocke** [comment]
Thanks for reporting the issue. It is a known issue of `rbs collection`.
`rbs collection` doesn't resolve stdlib's dependency so you need to resolve stdlib's dependency by hand. See "Resolve stdlib dependencies" section in https://github.com/ruby/rbs/pull/589 

So you need to add stdlib's dependencies of gems that your Gemfile.lock includes.
I have full list of the stdlib dependencies of `rails` gem. I guess you need to pick up some gems from the following list for Active Support.

```yaml
gems:
  - name: pathname
  - name: logger
  - name: mutex_m
  - name: date
  - name: monitor
  - name: singleton
  - name: tsort
  - name: time
  - name: set
```

Sorry for the inconvenience. I'll fix the problem soon (before Ruby 3.1, I hope).

**Comment by ybiquitous** [comment]
@pocke Thank you for the kind instructions! I'll try it later. Please feel free to close this issue if not needed. 😄

**Comment by ybiquitous** [comment]
When I add the following lines to `Gemfile`, the error is solved!

```ruby
gem "date"
gem "logger"
gem "monitor"
gem "mutex_m"
gem "pathname"
gem "set"
gem "singleton"
gem "time"
gem "tsort"
```
