### ISSUE TITLE
steep check crashes and hangs with RuntimeError when namespace modules are not defined

### ISSUE THREAD

**Issue by tlubz** [soutaro/steep#559]
I have a situation like this

api/foo_controller.rb

```ruby
class Api::FooController # activesupport constant resolution creates module Api here
  # ...
end
```

sig/api/foo_controller.rbs

```rbs
class Api::FooController
end
```

running `steep check` here hangs, outputting something like 

```
[Steep 0.52.0] [typecheck:typecheck@5] [background] Processing TypeCheckCodeJob for guid=ffaf7fdb-95c6-4bf3-89a0-59cc4ed81915, path=/approot/example/app/controllers/api/foo_controller.rb
[Steep 0.52.0] [typecheck:typecheck@5] [background] Unexpected error: RuntimeError
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rbs-2.3.2/lib/rbs/resolver/constant_resolver.rb:22:in `block in initialize'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rbs-2.3.2/lib/rbs/resolver/constant_resolver.rb:18:in `each'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rbs-2.3.2/lib/rbs/resolver/constant_resolver.rb:18:in `initialize'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rbs-2.3.2/lib/rbs/resolver/constant_resolver.rb:75:in `new'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rbs-2.3.2/lib/rbs/resolver/constant_resolver.rb:75:in `initialize'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/steep-0.52.0/lib/steep/services/type_check_service.rb:345:in `new'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/steep-0.52.0/lib/steep/services/type_check_service.rb:345:in `type_check'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/steep-0.52.0/lib/steep/services/type_check_service.rb:327:in `block in type_check_file'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:28:in `tagged'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `tagged'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/steep-0.52.0/lib/steep/services/type_check_service.rb:325:in `type_check_file'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/steep-0.52.0/lib/steep/services/type_check_service.rb:281:in `block (2 levels) in typecheck_source'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/steep-0.52.0/lib/steep.rb:166:in `measure'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/steep-0.52.0/lib/steep/services/type_check_service.rb:275:in `block in typecheck_source'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:28:in `tagged'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `tagged'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/steep-0.52.0/lib/steep/services/type_check_service.rb:274:in `typecheck_source'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/steep-0.52.0/lib/steep/server/type_check_worker.rb:197:in `handle_job'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/steep-0.52.0/lib/steep/server/base_worker.rb:54:in `block (2 levels) in run'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:28:in `tagged'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `tagged'
[Steep 0.52.0] [typecheck:typecheck@5] [background]   /approot/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/steep-0.52.0/lib/steep/server/base_worker.rb:44:in `block in run'
```

turns out, we need to add a new file, sig/api.rbs:

```rbs
module Api
end
```

It makes sense that it fails there, since its not using activesupport's magic constant resolution. However, it should not hang, and it should fail with a human-friendly message. IMO, this should be a type-validation error/warning, not a RuntimeError/crash.

setup:

steep-0.52.0
rbs-2.3.2
ruby-2.6.5
activesupport-5.2.6

**Comment by soutaro** [comment]
@tlubz Thanks for this report.

This is a duplication of #547, as @ksss says. Closing this.
