### ISSUE TITLE
How to diagnose this error?

### ISSUE THREAD

**Issue by thomthom** [soutaro/steep#619]
I'm trying out `sord` on a set of API stubs we have:
https://github.com/SketchUp/ruby-api-stubs

There's a bunch of warnings, which isn't unexpected, the docs originated from RDoc and not everything has been ported to YARD yet. However, Sord appear to complete processing, but end up throwing an error when generating the output. What I'm struggling with is figuring out what it is failing on. The docs include 100+ classes/modules and 2000+ methods, so it's non-trivial to narrow this own.

Any suggestions to what I can do to identify what is triggering this?

![image](https://user-images.githubusercontent.com/192418/181475806-a94d3754-6ae7-476e-ab36-1988a201255f.png)

```
[OMIT ] (Sketchup::AttributeDictionary#each) no YARD return type given, using untyped
[OMIT ] (Sketchup::AttributeDictionary#each_pair) no YARD return type given, using untyped
[OMIT ] (Sketchup::ComponentDefinition#save_as) no YARD type given for "*args", using untyped
[OMIT ] (Sketchup::ComponentDefinition#save_copy) no YARD type given for "*args", using untyped
[OMIT ] (Sketchup::RenderingOptionsObserver#onRenderingOptionsChanged) no YARD return type given, using untyped
[DONE ] Processed 2088 objects (146 namespaces and 1942 methods)
Parlour warning: RBS generation: 'type' is a keyword in RBS, renaming method parameter to '_type'
Parlour warning: RBS generation: 'extension' is a keyword in RBS, renaming method parameter to '_extension'
Parlour warning: RBS generation: 'top' is a keyword in RBS, renaming method parameter to '_top'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/parlour-5.0.0/lib/parlour/rbs_generator/parameter.rb:79:in `name_without_kind': unknown prefix (RuntimeError)
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10217/lib/types/private/methods/call_validation_2_7.rb:57:in `bind_call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10217/lib/types/private/methods/call_validation_2_7.rb:57:in `block in create_validator_method_fast0'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/parlour-5.0.0/lib/parlour/rbs_generator/parameter.rb:125:in `to_rbs_param'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10217/lib/types/private/methods/call_validation_2_7.rb:57:in `bind_call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10217/lib/types/private/methods/call_validation_2_7.rb:57:in `block in create_validator_method_fast0'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/parlour-5.0.0/lib/parlour/types.rb:564:in `map'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/parlour-5.0.0/lib/parlour/types.rb:564:in `generate_rbs'
```

**Comment by thomthom** [comment]
Ah!

So I patched Parlour to emit the name it was inspecting:
![image](https://user-images.githubusercontent.com/192418/181479313-1ea633b5-07a5-4b33-aac3-247ef4a4dfa6.png)

Which then yielded something I could work with:
![image](https://user-images.githubusercontent.com/192418/181479393-38a5fa81-80d1-40e3-9276-bcbbf7bb1475.png)

Turns out that some of our doc signatures was something like this:

```
# @overload foo(point, point, ...)
def foo(*args)
end
```

The `...` had been used to denote that minimum two points were expected with optionally more accepted. After removing these `sord` would succeed. I need to rework these `...` notations.

Maybe I'll put up a PR with Parlour with the error message change.
