### ISSUE TITLE
Exception when running with ruby 3.2

### ISSUE THREAD

**Issue by rnestler** [soutaro/steep#823]
When I try to use steep with ruby 3.2 I get the following exception:
```
 steep check
#<NameError: uninitialized constant RBS::Collection::Config::Lockfile>
  /home/raphael/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/steep-1.4.0/lib/steep/project/dsl.rb:234:in `target'
  Steepfile:3:in `block in parse'
  /home/raphael/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/steep-1.4.0/lib/steep/project/dsl.rb:211:in `instance_eval'
  /home/raphael/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/steep-1.4.0/lib/steep/project/dsl.rb:211:in `block in parse'
  /home/raphael/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:99:in `block in tagged'
  /home/raphael/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:37:in `tagged'
  /home/raphael/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:99:in `tagged'
  /home/raphael/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/steep-1.4.0/lib/steep/project/dsl.rb:210:in `parse'
  /home/raphael/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/steep-1.4.0/lib/steep/drivers/utils/driver_helper.rb:12:in `block in load_config'
  <internal:kernel>:90:in `tap'
  /home/raphael/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/steep-1.4.0/lib/steep/drivers/utils/driver_helper.rb:11:in `load_config'
  /home/raphael/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/steep-1.4.0/lib/steep/drivers/check.rb:25:in `run'
  /home/raphael/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/steep-1.4.0/lib/steep/cli.rb:120:in `process_check'
  /home/raphael/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/steep-1.4.0/lib/steep/cli.rb:60:in `run'
  /home/raphael/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/steep-1.4.0/exe/steep:11:in `<top (required)>'
  /home/raphael/.asdf/installs/ruby/3.2.2/bin/steep:25:in `load'
  /home/raphael/.asdf/installs/ruby/3.2.2/bin/steep:25:in `<main>'
```

**Comment by rnestler** [comment]
Ah the bundled rbs gem from Ruby 3.2 is too old: https://stdgems.org/rbs/. Updating the rbs gem solved it.
