### ISSUE TITLE
Bug: #<NoMethodError: undefined method `type' for nil:NilClass>

### ISSUE THREAD

**Issue by stereobooster** [soutaro/steep#9]
```ruby
class A; end
A.new.echo
```

```
steep check test4.rb
#<NoMethodError: undefined method `type' for nil:NilClass>
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/type_construction.rb:169:in `synthesize'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/type_construction.rb:443:in `block in synthesize'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/type_construction.rb:442:in `tap'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/type_construction.rb:442:in `synthesize'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/type_construction.rb:172:in `block in synthesize'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/type_construction.rb:737:in `block in each_child_node'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/type_construction.rb:735:in `each'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/type_construction.rb:735:in `each_child_node'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/type_construction.rb:171:in `each'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/type_construction.rb:171:in `map'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/type_construction.rb:171:in `synthesize'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/drivers/check.rb:65:in `block in run'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/drivers/check.rb:44:in `each'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/drivers/check.rb:44:in `run'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/cli.rb:76:in `process_check'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/lib/steep/cli.rb:41:in `run'
  /opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/steep-0.1.0.pre/exe/steep:11:in `<top (required)>'
  /opt/boxen/rbenv/versions/2.4.0/bin/steep:22:in `load'
  /opt/boxen/rbenv/versions/2.4.0/bin/steep:22:in `<main>'
```

https://github.com/stereobooster/diamondback-ruby/tree/master/examples#4

**Comment by soutaro** [comment]
Oh...

Thanks. I will fix the class body handling if it is empty...

**Comment by meganemura** [comment]
It doesn't seem to be reproduced this problem now, so I think we can close this issue.
https://github.com/meganemura/steep-sandbox/tree/master/issue-9

```
$ bundle exec steep version
0.17.1
$ bundle exec steep check
reproduce1.rb:2:0: FallbackAny (A)
```
