### ISSUE TITLE
optional method arg named `_` implodes `steep check`

### ISSUE THREAD

**Issue by ParadoxV5** [soutaro/steep#913]
does not affect and mandatory `_` arg and optional not-`_` args

---

Ruby:
```ruby
def m(x = nil) = nil
```

RBS:
```rbs
class Object
  def m: (?untyped) -> void
end
```

<details><summary><code>steep check</code>:</summary>

```
# Type checking files:

......................................................................[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)] Unexpected error: #<RuntimeError: Unexpected variable name: _>
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_inference/type_env.rb:92:in `[]'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:1308:in `block (2 levels) in synthesize'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   <internal:kernel>:148:in `yield_self'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:1304:in `block in synthesize'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:694:in `synthesize'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:3245:in `block in synthesize_children'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/node_helper.rb:7:in `block in each_child_node'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/node_helper.rb:5:in `each'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/node_helper.rb:5:in `each_child_node'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:3243:in `synthesize_children'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:963:in `block (3 levels) in synthesize'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:280:in `block in with_method_constr'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:51:in `push_variable_bounds'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:279:in `with_method_constr'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:942:in `block (2 levels) in synthesize'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   <internal:kernel>:148:in `yield_self'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:937:in `block in synthesize'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:694:in `synthesize'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/services/type_check_service.rb:393:in `type_check'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/services/type_check_service.rb:329:in `block in type_check_file'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/services/type_check_service.rb:327:in `type_check_file'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/services/type_check_service.rb:283:in `block (2 levels) in typecheck_source'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep.rb:180:in `measure'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/services/type_check_service.rb:277:in `block in typecheck_source'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/services/type_check_service.rb:276:in `typecheck_source'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/server/type_check_worker.rb:198:in `handle_job'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/server/base_worker.rb:56:in `block (2 levels) in run'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:37:in `tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `tagged'
[Steep 1.5.3] [typecheck:typecheck@6] [background] [#typecheck_source(path=underscore_arg.rb)] [#type_check_file(underscore_arg.rb@lib)] [synthesize:(1:1)] [synthesize:(1:7)]   /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/server/base_worker.rb:46:in `block in run'
F.............

underscore_arg.rb:1:6: [error] UnexpectedError: Unexpected variable name: _(RuntimeError)
│ 1. /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_inference/type_env.rb:92:in `[]'
│ 2. /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:1308:in `block (2 levels) in synthesize'
│ 3. <internal:kernel>:148:in `yield_self'
│ 4. /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:1304:in `block in synthesize'
│ 5. /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'
│ 6. /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:37:in `tagged'
│ 7. /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `tagged'
│ 8. /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:694:in `synthesize'
│ 9. /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:3245:in `block in synthesize_children'
│ 10. /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/node_helper.rb:7:in `block in each_child_node'
│ 11. /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/node_helper.rb:5:in `each'
│ 12. /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/node_helper.rb:5:in `each_child_node'
│ 13. /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:3243:in `synthesize_children'
│ 14. /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:963:in `block (3 levels) in synthesize'
│ 15. /usr/local/lib/ruby/gems/3.2.0/gems/steep-1.5.3/lib/steep/type_construction.rb:280:in `block in with_method_constr'
│   (28 more backtrace)
│
│ Diagnostic ID: Ruby::UnexpectedError
│
└ def m(_ = nil) = nil
        ~~~~~~~

Detected 1 problem from 1 file
```

</details>

**Comment by ParadoxV5** [comment]
Related: #659
