### ISSUE TITLE
Steep crashes when a void or top is passed to an interface argument

### ISSUE THREAD

**Issue by pocke** [soutaro/steep#918]
# Reproduce 

```rbs
# RBS
class C
  def self.void:    () -> void
  def self.top:     () -> top

  def self.f: (_ToI) -> void
end
```

```ruby
# Ruby

C.f C.void
C.f C.top
```

```ruby
# Steepfile
D = Steep::Diagnostic
target :lib do
  signature "."
  check '.'
  configure_code_diagnostics(D::Ruby.all_error)
end
```

With the above files, Steep crashes with the following errors.

```console
test.rb:1:0: [error] UnexpectedError: (RuntimeError)
│ 1. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:413:in `block (2 levels) in check_type0'
│ 2. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/relation.rb:88:in `map'
│ 3. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:403:in `block in check_type0'
│ 4. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/result.rb:57:in `initialize'
│ 5. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/result.rb:295:in `new'
│ 6. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/result.rb:295:in `Expand'
│ 7. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:401:in `check_type0'
│ 8. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:203:in `block (2 levels) in check_type'
│ 9. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:35:in `push_assumption'
│ 10. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:202:in `block in check_type'
│ 11. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'
│ 12. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:37:in `tagged'
│ 13. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `tagged'
│ 14. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:192:in `check_type'
│ 15. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:185:in `block in check'
│   (63 more backtrace)
│
│ Diagnostic ID: Ruby::UnexpectedError
│
└ C.f C.void
  ~~~~~~~~~~

test.rb:2:0: [error] UnexpectedError: (RuntimeError)
│ 1. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:413:in `block (2 levels) in check_type0'
│ 2. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/relation.rb:88:in `map'
│ 3. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:403:in `block in check_type0'
│ 4. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/result.rb:57:in `initialize'
│ 5. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/result.rb:295:in `new'
│ 6. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/result.rb:295:in `Expand'
│ 7. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:401:in `check_type0'
│ 8. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:203:in `block (2 levels) in check_type'
│ 9. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:35:in `push_assumption'
│ 10. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:202:in `block in check_type'
│ 11. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'
│ 12. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:37:in `tagged'
│ 13. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `tagged'
│ 14. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:192:in `check_type'
│ 15. /Users/kuwabara.masataka/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/steep-1.5.3/lib/steep/subtyping/check.rb:185:in `block in check'
│   (60 more backtrace)
│
│ Diagnostic ID: Ruby::UnexpectedError
│
└ C.f C.top
  ~~~~~~~~~
```

I can reproduce this problem with Steep v1.5.3 and the master branch (479d4fdd21745e72be0d4993f236c4718ae4afc6)

# Cause

I guess the cause is `Bulder#shape` returns `nil` when the type is a `void` or `top`.

https://github.com/soutaro/steep/blob/479d4fdd21745e72be0d4993f236c4718ae4afc6/lib/steep/interface/builder.rb#L169-L170

But I'm not sure how to fix this problem...

**Comment by ParadoxV5** [comment]
Method args are “`in`” and therefore contravariant, which means not valid as args that expect a subclass.

That said, Steep should report “Cannot pass a value of type `top`/`void` as an argument of type `::_ToI`” rather than blow up.
